0,1
2023-11-18 01:05:03
/apps/all/binutils/2.32-GCCcore-8.3.0/lib:/apps/all/zlib/1.2.11-GCCcore-8.3.0/lib:/apps/all/GCCcore/8.3.0/lib64:/apps/all/GCCcore/8.3.0/lib:/apps/all/CUDA/11.7.0/nvvm/lib64:/apps/all/CUDA/11.7.0/extras/CUPTI/lib64:/apps/all/CUDA/11.7.0/lib
acn07 0,1
Sat Nov 18 01:05:04 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off | 00000000:07:00.0 Off |                    0 |
| N/A   27C    P0              50W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-40GB          Off | 00000000:0B:00.0 Off |                    0 |
| N/A   27C    P0              54W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
2.0.1+cu117
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
Traceback (most recent call last):
  File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/run_beit3_finetuning_al.py", line 25, in <module>
    from engine_for_finetuning import train_one_epoch, get_handler, evaluate, evaluate_train
  File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/engine_for_finetuning.py", line 20, in <module>
    from datasets import get_sentencepiece_model_for_beit3
  File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/datasets.py", line 20, in <module>
Traceback (most recent call last):
  File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/run_beit3_finetuning_al.py", line 25, in <module>
    from engine_for_finetuning import train_one_epoch, get_handler, evaluate, evaluate_train
      File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/engine_for_finetuning.py", line 20, in <module>
import utils
  File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/utils.py", line 24, in <module>
    from datasets import get_sentencepiece_model_for_beit3
  File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/datasets.py", line 20, in <module>
    import utils
      File "/scratch/project/dd-23-80/code/beit3/beit3/beit3/utils.py", line 24, in <module>
from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 87204) of binary: /scratch/project/dd-23-80/envs/beit3_new/bin/python3.9
Traceback (most recent call last):
  File "/scratch/project/dd-23-80/envs/beit3_new/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/scratch/project/dd-23-80/envs/beit3_new/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/scratch/project/dd-23-80/envs/beit3_new/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/scratch/project/dd-23-80/envs/beit3_new/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/scratch/project/dd-23-80/envs/beit3_new/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scratch/project/dd-23-80/envs/beit3_new/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_beit3_finetuning_al.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-18_01:05:12
  host      : acn07.karolina.it4i.cz
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 87205)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-18_01:05:12
  host      : acn07.karolina.it4i.cz
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 87204)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
